---
components:
  - name: website
    type: service
    image: node:16-alpine
    root: iss-position-noop/
    build:
      steps:
        - directory: /iss-noop-position
        - copy: package*.json
          destination: ./
        - run: npm i
        - copy: .
    runtime:
      command: npm start
