---
components:
  - name: website
    type: service
    image: node:16-alpine
    root: iss-position-noop/
    build:
      steps:
        - directory: /iss-position-noop
        - copy: package*.json
          destination: ./
        - run: npm i
        - copy: .
        - run: npm run build
        - image: nginx:1-alpine
          stage: nginx
        - copy: iss-position-noop/build
          destination: /usr/share/nginx/html/
          from: main
        - copy: nginx.conf
          destination: /etc/nginx
    ports:
      - "80:80"
    runtime:
      command: 'nginx -g "daemon off;"'
      variables:
        NGINX_ENTRYPOINT_QUIET_LOGS: "1"
